// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit manually
// Run: node scripts/generate-icons.mjs
// SVG data sourced from lucide-react (https://lucide.dev) — ISC License
// Copyright (c) for portions held by Cole Bemis 2013-2022 (Feather, MIT).
// All other copyright (c) Lucide Contributors 2022.
import { createElement, forwardRef } from 'react'
import type { SVGProps } from 'react'

export type LucideProps = Omit<SVGProps<SVGSVGElement>, 'ref'> & {
  size?: number | string
  strokeWidth?: number | string
  absoluteStrokeWidth?: boolean
  color?: string
}

export type LucideIcon = ReturnType<typeof createIcon>

function createIcon(name: string, nodes: [string, Record<string, string | number>][]) {
  const Icon = forwardRef<SVGSVGElement, LucideProps>(
    ({ size = 24, strokeWidth = 2, color, absoluteStrokeWidth, className, ...props }, ref) =>
      createElement(
        'svg',
        {
          ref,
          xmlns: 'http://www.w3.org/2000/svg',
          width: size,
          height: size,
          viewBox: '0 0 24 24',
          fill: 'none',
          stroke: color ?? 'currentColor',
          strokeWidth: absoluteStrokeWidth
            ? (Number(strokeWidth) * 24) / Number(size)
            : strokeWidth,
          strokeLinecap: 'round',
          strokeLinejoin: 'round',
          className: className ? `lucide lucide-${name} ${className}` : `lucide lucide-${name}`,
          ...props,
        },
        ...nodes.map(([tag, attrs], i) => createElement(tag, { key: i, ...attrs }))
      )
  )
  Icon.displayName = name
  return Icon
}

export const AlertCircle = /*#__PURE__*/createIcon('alert-circle', [["circle",{"cx":"12","cy":"12","r":"10"}],["line",{"x1":"12","x2":"12","y1":"8","y2":"12"}],["line",{"x1":"12","x2":"12.01","y1":"16","y2":"16"}]])
export const AlertTriangle = /*#__PURE__*/createIcon('alert-triangle', [["path",{"d":"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"}],["path",{"d":"M12 9v4"}],["path",{"d":"M12 17h.01"}]])
export const ArrowDown = /*#__PURE__*/createIcon('arrow-down', [["path",{"d":"M12 5v14"}],["path",{"d":"m19 12-7 7-7-7"}]])
export const ArrowLeft = /*#__PURE__*/createIcon('arrow-left', [["path",{"d":"m12 19-7-7 7-7"}],["path",{"d":"M19 12H5"}]])
export const ArrowRight = /*#__PURE__*/createIcon('arrow-right', [["path",{"d":"M5 12h14"}],["path",{"d":"m12 5 7 7-7 7"}]])
export const ArrowRightToLine = /*#__PURE__*/createIcon('arrow-right-to-line', [["path",{"d":"M17 12H3"}],["path",{"d":"m11 18 6-6-6-6"}],["path",{"d":"M21 5v14"}]])
export const ArrowUp = /*#__PURE__*/createIcon('arrow-up', [["path",{"d":"m5 12 7-7 7 7"}],["path",{"d":"M12 19V5"}]])
export const Axis3D = /*#__PURE__*/createIcon('axis-3-d', [["path",{"d":"M4 4v16h16"}],["path",{"d":"m4 20 7-7"}]])
export const Box = /*#__PURE__*/createIcon('box', [["path",{"d":"M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"}],["path",{"d":"m3.3 7 8.7 5 8.7-5"}],["path",{"d":"M12 22V12"}]])
export const Check = /*#__PURE__*/createIcon('check', [["path",{"d":"M20 6 9 17l-5-5"}]])
export const CheckCircle = /*#__PURE__*/createIcon('check-circle', [["path",{"d":"M21.801 10A10 10 0 1 1 17 3.335"}],["path",{"d":"m9 11 3 3L22 4"}]])
export const CheckCircle2 = /*#__PURE__*/createIcon('check-circle-2', [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"m9 12 2 2 4-4"}]])
export const ChevronDown = /*#__PURE__*/createIcon('chevron-down', [["path",{"d":"m6 9 6 6 6-6"}]])
export const ChevronLeft = /*#__PURE__*/createIcon('chevron-left', [["path",{"d":"m15 18-6-6 6-6"}]])
export const ChevronRight = /*#__PURE__*/createIcon('chevron-right', [["path",{"d":"m9 18 6-6-6-6"}]])
export const ChevronUp = /*#__PURE__*/createIcon('chevron-up', [["path",{"d":"m18 15-6-6-6 6"}]])
export const ChevronsDown = /*#__PURE__*/createIcon('chevrons-down', [["path",{"d":"m7 6 5 5 5-5"}],["path",{"d":"m7 13 5 5 5-5"}]])
export const CircleDot = /*#__PURE__*/createIcon('circle-dot', [["circle",{"cx":"12","cy":"12","r":"10"}],["circle",{"cx":"12","cy":"12","r":"1"}]])
export const CircuitBoard = /*#__PURE__*/createIcon('circuit-board', [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M11 9h4a2 2 0 0 0 2-2V3"}],["circle",{"cx":"9","cy":"9","r":"2"}],["path",{"d":"M7 21v-4a2 2 0 0 1 2-2h4"}],["circle",{"cx":"15","cy":"15","r":"2"}]])
export const Clipboard = /*#__PURE__*/createIcon('clipboard', [["rect",{"width":"8","height":"4","x":"8","y":"2","rx":"1","ry":"1"}],["path",{"d":"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"}]])
export const ClipboardCheck = /*#__PURE__*/createIcon('clipboard-check', [["rect",{"width":"8","height":"4","x":"8","y":"2","rx":"1","ry":"1"}],["path",{"d":"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"}],["path",{"d":"m9 14 2 2 4-4"}]])
export const CloudDrizzle = /*#__PURE__*/createIcon('cloud-drizzle', [["path",{"d":"M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242"}],["path",{"d":"M8 19v1"}],["path",{"d":"M8 14v1"}],["path",{"d":"M16 19v1"}],["path",{"d":"M16 14v1"}],["path",{"d":"M12 21v1"}],["path",{"d":"M12 16v1"}]])
export const Code2 = /*#__PURE__*/createIcon('code-2', [["path",{"d":"m18 16 4-4-4-4"}],["path",{"d":"m6 8-4 4 4 4"}],["path",{"d":"m14.5 4-5 16"}]])
export const Cpu = /*#__PURE__*/createIcon('cpu', [["rect",{"width":"16","height":"16","x":"4","y":"4","rx":"2"}],["rect",{"width":"6","height":"6","x":"9","y":"9","rx":"1"}],["path",{"d":"M15 2v2"}],["path",{"d":"M15 20v2"}],["path",{"d":"M2 15h2"}],["path",{"d":"M2 9h2"}],["path",{"d":"M20 15h2"}],["path",{"d":"M20 9h2"}],["path",{"d":"M9 2v2"}],["path",{"d":"M9 20v2"}]])
export const Crosshair = /*#__PURE__*/createIcon('crosshair', [["circle",{"cx":"12","cy":"12","r":"10"}],["line",{"x1":"22","x2":"18","y1":"12","y2":"12"}],["line",{"x1":"6","x2":"2","y1":"12","y2":"12"}],["line",{"x1":"12","x2":"12","y1":"6","y2":"2"}],["line",{"x1":"12","x2":"12","y1":"22","y2":"18"}]])
export const DoorOpen = /*#__PURE__*/createIcon('door-open', [["path",{"d":"M13 4h3a2 2 0 0 1 2 2v14"}],["path",{"d":"M2 20h3"}],["path",{"d":"M13 20h9"}],["path",{"d":"M10 12v.01"}],["path",{"d":"M13 4.562v16.157a1 1 0 0 1-1.242.97L5 20V5.562a2 2 0 0 1 1.515-1.94l4-1A2 2 0 0 1 13 4.561Z"}]])
export const Download = /*#__PURE__*/createIcon('download', [["path",{"d":"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"}],["polyline",{"points":"7 10 12 15 17 10"}],["line",{"x1":"12","x2":"12","y1":"15","y2":"3"}]])
export const Eye = /*#__PURE__*/createIcon('eye', [["path",{"d":"M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"}],["circle",{"cx":"12","cy":"12","r":"3"}]])
export const File = /*#__PURE__*/createIcon('file', [["path",{"d":"M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"}],["path",{"d":"M14 2v4a2 2 0 0 0 2 2h4"}]])
export const FileCode = /*#__PURE__*/createIcon('file-code', [["path",{"d":"M10 12.5 8 15l2 2.5"}],["path",{"d":"m14 12.5 2 2.5-2 2.5"}],["path",{"d":"M14 2v4a2 2 0 0 0 2 2h4"}],["path",{"d":"M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7z"}]])
export const FileCode2 = /*#__PURE__*/createIcon('file-code-2', [["path",{"d":"M4 22h14a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v4"}],["path",{"d":"M14 2v4a2 2 0 0 0 2 2h4"}],["path",{"d":"m5 12-3 3 3 3"}],["path",{"d":"m9 18 3-3-3-3"}]])
export const FilePlus = /*#__PURE__*/createIcon('file-plus', [["path",{"d":"M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"}],["path",{"d":"M14 2v4a2 2 0 0 0 2 2h4"}],["path",{"d":"M9 15h6"}],["path",{"d":"M12 18v-6"}]])
export const Folder = /*#__PURE__*/createIcon('folder', [["path",{"d":"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"}]])
export const FolderOpen = /*#__PURE__*/createIcon('folder-open', [["path",{"d":"m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2"}]])
export const FolderPlus = /*#__PURE__*/createIcon('folder-plus', [["path",{"d":"M12 10v6"}],["path",{"d":"M9 13h6"}],["path",{"d":"M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"}]])
export const Gauge = /*#__PURE__*/createIcon('gauge', [["path",{"d":"m12 14 4-4"}],["path",{"d":"M3.34 19a10 10 0 1 1 17.32 0"}]])
export const Globe = /*#__PURE__*/createIcon('globe', [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"}],["path",{"d":"M2 12h20"}]])
export const Grid3X3 = /*#__PURE__*/createIcon('grid-3-x-3', [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M3 9h18"}],["path",{"d":"M3 15h18"}],["path",{"d":"M9 3v18"}],["path",{"d":"M15 3v18"}]])
export const Hand = /*#__PURE__*/createIcon('hand', [["path",{"d":"M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2"}],["path",{"d":"M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2"}],["path",{"d":"M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8"}],["path",{"d":"M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15"}]])
export const HardDrive = /*#__PURE__*/createIcon('hard-drive', [["line",{"x1":"22","x2":"2","y1":"12","y2":"12"}],["path",{"d":"M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"}],["line",{"x1":"6","x2":"6.01","y1":"16","y2":"16"}],["line",{"x1":"10","x2":"10.01","y1":"16","y2":"16"}]])
export const Hash = /*#__PURE__*/createIcon('hash', [["line",{"x1":"4","x2":"20","y1":"9","y2":"9"}],["line",{"x1":"4","x2":"20","y1":"15","y2":"15"}],["line",{"x1":"10","x2":"8","y1":"3","y2":"21"}],["line",{"x1":"16","x2":"14","y1":"3","y2":"21"}]])
export const Heart = /*#__PURE__*/createIcon('heart', [["path",{"d":"M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"}]])
export const HelpCircle = /*#__PURE__*/createIcon('help-circle', [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"}],["path",{"d":"M12 17h.01"}]])
export const Home = /*#__PURE__*/createIcon('home', [["path",{"d":"M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"}],["path",{"d":"M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"}]])
export const Info = /*#__PURE__*/createIcon('info', [["circle",{"cx":"12","cy":"12","r":"10"}],["path",{"d":"M12 16v-4"}],["path",{"d":"M12 8h.01"}]])
export const LayoutDashboard = /*#__PURE__*/createIcon('layout-dashboard', [["rect",{"width":"7","height":"9","x":"3","y":"3","rx":"1"}],["rect",{"width":"7","height":"5","x":"14","y":"3","rx":"1"}],["rect",{"width":"7","height":"9","x":"14","y":"12","rx":"1"}],["rect",{"width":"7","height":"5","x":"3","y":"16","rx":"1"}]])
export const Lightbulb = /*#__PURE__*/createIcon('lightbulb', [["path",{"d":"M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5"}],["path",{"d":"M9 18h6"}],["path",{"d":"M10 22h4"}]])
export const ListStart = /*#__PURE__*/createIcon('list-start', [["path",{"d":"M16 12H3"}],["path",{"d":"M16 18H3"}],["path",{"d":"M10 6H3"}],["path",{"d":"M21 18V8a2 2 0 0 0-2-2h-5"}],["path",{"d":"m16 8-2-2 2-2"}]])
export const Loader2 = /*#__PURE__*/createIcon('loader-2', [["path",{"d":"M21 12a9 9 0 1 1-6.219-8.56"}]])
export const LoaderCircle = /*#__PURE__*/createIcon('loader-circle', [["path",{"d":"M21 12a9 9 0 1 1-6.219-8.56"}]])
export const Maximize = /*#__PURE__*/createIcon('maximize', [["path",{"d":"M8 3H5a2 2 0 0 0-2 2v3"}],["path",{"d":"M21 8V5a2 2 0 0 0-2-2h-3"}],["path",{"d":"M3 16v3a2 2 0 0 0 2 2h3"}],["path",{"d":"M16 21h3a2 2 0 0 0 2-2v-3"}]])
export const Maximize2 = /*#__PURE__*/createIcon('maximize-2', [["polyline",{"points":"15 3 21 3 21 9"}],["polyline",{"points":"9 21 3 21 3 15"}],["line",{"x1":"21","x2":"14","y1":"3","y2":"10"}],["line",{"x1":"3","x2":"10","y1":"21","y2":"14"}]])
export const Minimize = /*#__PURE__*/createIcon('minimize', [["path",{"d":"M8 3v3a2 2 0 0 1-2 2H3"}],["path",{"d":"M21 8h-3a2 2 0 0 1-2-2V3"}],["path",{"d":"M3 16h3a2 2 0 0 1 2 2v3"}],["path",{"d":"M16 21v-3a2 2 0 0 1 2-2h3"}]])
export const Minus = /*#__PURE__*/createIcon('minus', [["path",{"d":"M5 12h14"}]])
export const Monitor = /*#__PURE__*/createIcon('monitor', [["rect",{"width":"20","height":"14","x":"2","y":"3","rx":"2"}],["line",{"x1":"8","x2":"16","y1":"21","y2":"21"}],["line",{"x1":"12","x2":"12","y1":"17","y2":"21"}]])
export const Moon = /*#__PURE__*/createIcon('moon', [["path",{"d":"M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"}]])
export const Navigation = /*#__PURE__*/createIcon('navigation', [["polygon",{"points":"3 11 22 2 13 21 11 13 3 11"}]])
export const Orbit = /*#__PURE__*/createIcon('orbit', [["circle",{"cx":"12","cy":"12","r":"3"}],["circle",{"cx":"19","cy":"5","r":"2"}],["circle",{"cx":"5","cy":"19","r":"2"}],["path",{"d":"M10.4 21.9a10 10 0 0 0 9.941-15.416"}],["path",{"d":"M13.5 2.1a10 10 0 0 0-9.841 15.416"}]])
export const PanelBottom = /*#__PURE__*/createIcon('panel-bottom', [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M3 15h18"}]])
export const PanelRight = /*#__PURE__*/createIcon('panel-right', [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}],["path",{"d":"M15 3v18"}]])
export const Pause = /*#__PURE__*/createIcon('pause', [["rect",{"x":"14","y":"4","width":"4","height":"16","rx":"1"}],["rect",{"x":"6","y":"4","width":"4","height":"16","rx":"1"}]])
export const Pencil = /*#__PURE__*/createIcon('pencil', [["path",{"d":"M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z"}],["path",{"d":"m15 5 4 4"}]])
export const Pin = /*#__PURE__*/createIcon('pin', [["path",{"d":"M12 17v5"}],["path",{"d":"M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z"}]])
export const Play = /*#__PURE__*/createIcon('play', [["polygon",{"points":"6 3 20 12 6 21 6 3"}]])
export const Plus = /*#__PURE__*/createIcon('plus', [["path",{"d":"M5 12h14"}],["path",{"d":"M12 5v14"}]])
export const Power = /*#__PURE__*/createIcon('power', [["path",{"d":"M12 2v10"}],["path",{"d":"M18.4 6.6a9 9 0 1 1-12.77.04"}]])
export const PowerOff = /*#__PURE__*/createIcon('power-off', [["path",{"d":"M18.36 6.64A9 9 0 0 1 20.77 15"}],["path",{"d":"M6.16 6.16a9 9 0 1 0 12.68 12.68"}],["path",{"d":"M12 2v4"}],["path",{"d":"m2 2 20 20"}]])
export const Puzzle = /*#__PURE__*/createIcon('puzzle', [["path",{"d":"M15.39 4.39a1 1 0 0 0 1.68-.474 2.5 2.5 0 1 1 3.014 3.015 1 1 0 0 0-.474 1.68l1.683 1.682a2.414 2.414 0 0 1 0 3.414L19.61 15.39a1 1 0 0 1-1.68-.474 2.5 2.5 0 1 0-3.014 3.015 1 1 0 0 1 .474 1.68l-1.683 1.682a2.414 2.414 0 0 1-3.414 0L8.61 19.61a1 1 0 0 0-1.68.474 2.5 2.5 0 1 1-3.014-3.015 1 1 0 0 0 .474-1.68l-1.683-1.682a2.414 2.414 0 0 1 0-3.414L4.39 8.61a1 1 0 0 1 1.68.474 2.5 2.5 0 1 0 3.014-3.015 1 1 0 0 1-.474-1.68l1.683-1.682a2.414 2.414 0 0 1 3.414 0z"}]])
export const Radio = /*#__PURE__*/createIcon('radio', [["path",{"d":"M4.9 19.1C1 15.2 1 8.8 4.9 4.9"}],["path",{"d":"M7.8 16.2c-2.3-2.3-2.3-6.1 0-8.5"}],["circle",{"cx":"12","cy":"12","r":"2"}],["path",{"d":"M16.2 7.8c2.3 2.3 2.3 6.1 0 8.5"}],["path",{"d":"M19.1 4.9C23 8.8 23 15.1 19.1 19"}]])
export const Redo2 = /*#__PURE__*/createIcon('redo-2', [["path",{"d":"m15 14 5-5-5-5"}],["path",{"d":"M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13"}]])
export const RefreshCw = /*#__PURE__*/createIcon('refresh-cw', [["path",{"d":"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"}],["path",{"d":"M21 3v5h-5"}],["path",{"d":"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"}],["path",{"d":"M8 16H3v5"}]])
export const RotateCcw = /*#__PURE__*/createIcon('rotate-ccw', [["path",{"d":"M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"}],["path",{"d":"M3 3v5h5"}]])
export const Save = /*#__PURE__*/createIcon('save', [["path",{"d":"M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z"}],["path",{"d":"M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7"}],["path",{"d":"M7 3v4a1 1 0 0 0 1 1h7"}]])
export const Search = /*#__PURE__*/createIcon('search', [["circle",{"cx":"11","cy":"11","r":"8"}],["path",{"d":"m21 21-4.3-4.3"}]])
export const Server = /*#__PURE__*/createIcon('server', [["rect",{"width":"20","height":"8","x":"2","y":"2","rx":"2","ry":"2"}],["rect",{"width":"20","height":"8","x":"2","y":"14","rx":"2","ry":"2"}],["line",{"x1":"6","x2":"6.01","y1":"6","y2":"6"}],["line",{"x1":"6","x2":"6.01","y1":"18","y2":"18"}]])
export const Settings = /*#__PURE__*/createIcon('settings', [["path",{"d":"M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"}],["circle",{"cx":"12","cy":"12","r":"3"}]])
export const Settings2 = /*#__PURE__*/createIcon('settings-2', [["path",{"d":"M20 7h-9"}],["path",{"d":"M14 17H5"}],["circle",{"cx":"17","cy":"17","r":"3"}],["circle",{"cx":"7","cy":"7","r":"3"}]])
export const ShieldCheck = /*#__PURE__*/createIcon('shield-check', [["path",{"d":"M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"}],["path",{"d":"m9 12 2 2 4-4"}]])
export const Sliders = /*#__PURE__*/createIcon('sliders', [["line",{"x1":"4","x2":"4","y1":"21","y2":"14"}],["line",{"x1":"4","x2":"4","y1":"10","y2":"3"}],["line",{"x1":"12","x2":"12","y1":"21","y2":"12"}],["line",{"x1":"12","x2":"12","y1":"8","y2":"3"}],["line",{"x1":"20","x2":"20","y1":"21","y2":"16"}],["line",{"x1":"20","x2":"20","y1":"12","y2":"3"}],["line",{"x1":"2","x2":"6","y1":"14","y2":"14"}],["line",{"x1":"10","x2":"14","y1":"8","y2":"8"}],["line",{"x1":"18","x2":"22","y1":"16","y2":"16"}]])
export const SlidersHorizontal = /*#__PURE__*/createIcon('sliders-horizontal', [["line",{"x1":"21","x2":"14","y1":"4","y2":"4"}],["line",{"x1":"10","x2":"3","y1":"4","y2":"4"}],["line",{"x1":"21","x2":"12","y1":"12","y2":"12"}],["line",{"x1":"8","x2":"3","y1":"12","y2":"12"}],["line",{"x1":"21","x2":"16","y1":"20","y2":"20"}],["line",{"x1":"12","x2":"3","y1":"20","y2":"20"}],["line",{"x1":"14","x2":"14","y1":"2","y2":"6"}],["line",{"x1":"8","x2":"8","y1":"10","y2":"14"}],["line",{"x1":"16","x2":"16","y1":"18","y2":"22"}]])
export const Square = /*#__PURE__*/createIcon('square', [["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2"}]])
export const StepForward = /*#__PURE__*/createIcon('step-forward', [["line",{"x1":"6","x2":"6","y1":"4","y2":"20"}],["polygon",{"points":"10,4 20,12 10,20"}]])
export const Store = /*#__PURE__*/createIcon('store', [["path",{"d":"m2 7 4.41-4.41A2 2 0 0 1 7.83 2h8.34a2 2 0 0 1 1.42.59L22 7"}],["path",{"d":"M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"}],["path",{"d":"M15 22v-4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v4"}],["path",{"d":"M2 7h20"}],["path",{"d":"M22 7v3a2 2 0 0 1-2 2a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 16 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 12 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 8 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 4 12a2 2 0 0 1-2-2V7"}]])
export const Sun = /*#__PURE__*/createIcon('sun', [["circle",{"cx":"12","cy":"12","r":"4"}],["path",{"d":"M12 2v2"}],["path",{"d":"M12 20v2"}],["path",{"d":"m4.93 4.93 1.41 1.41"}],["path",{"d":"m17.66 17.66 1.41 1.41"}],["path",{"d":"M2 12h2"}],["path",{"d":"M20 12h2"}],["path",{"d":"m6.34 17.66-1.41 1.41"}],["path",{"d":"m19.07 4.93-1.41 1.41"}]])
export const Target = /*#__PURE__*/createIcon('target', [["circle",{"cx":"12","cy":"12","r":"10"}],["circle",{"cx":"12","cy":"12","r":"6"}],["circle",{"cx":"12","cy":"12","r":"2"}]])
export const TerminalSquare = /*#__PURE__*/createIcon('terminal-square', [["path",{"d":"m7 11 2-2-2-2"}],["path",{"d":"M11 13h4"}],["rect",{"width":"18","height":"18","x":"3","y":"3","rx":"2","ry":"2"}]])
export const Trash2 = /*#__PURE__*/createIcon('trash-2', [["path",{"d":"M3 6h18"}],["path",{"d":"M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"}],["path",{"d":"M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"}],["line",{"x1":"10","x2":"10","y1":"11","y2":"17"}],["line",{"x1":"14","x2":"14","y1":"11","y2":"17"}]])
export const TriangleAlert = /*#__PURE__*/createIcon('triangle-alert', [["path",{"d":"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"}],["path",{"d":"M12 9v4"}],["path",{"d":"M12 17h.01"}]])
export const Turtle = /*#__PURE__*/createIcon('turtle', [["path",{"d":"m12 10 2 4v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-3a8 8 0 1 0-16 0v3a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-3l2-4h4Z"}],["path",{"d":"M4.82 7.9 8 10"}],["path",{"d":"M15.18 7.9 12 10"}],["path",{"d":"M16.93 10H20a2 2 0 0 1 0 4H2"}]])
export const Undo2 = /*#__PURE__*/createIcon('undo-2', [["path",{"d":"M9 14 4 9l5-5"}],["path",{"d":"M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11"}]])
export const Upload = /*#__PURE__*/createIcon('upload', [["path",{"d":"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"}],["polyline",{"points":"17 8 12 3 7 8"}],["line",{"x1":"12","x2":"12","y1":"3","y2":"15"}]])
export const Waves = /*#__PURE__*/createIcon('waves', [["path",{"d":"M2 6c.6.5 1.2 1 2.5 1C7 7 7 5 9.5 5c2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"}],["path",{"d":"M2 12c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"}],["path",{"d":"M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1"}]])
export const Wifi = /*#__PURE__*/createIcon('wifi', [["path",{"d":"M12 20h.01"}],["path",{"d":"M2 8.82a15 15 0 0 1 20 0"}],["path",{"d":"M5 12.859a10 10 0 0 1 14 0"}],["path",{"d":"M8.5 16.429a5 5 0 0 1 7 0"}]])
export const WifiOff = /*#__PURE__*/createIcon('wifi-off', [["path",{"d":"M12 20h.01"}],["path",{"d":"M8.5 16.429a5 5 0 0 1 7 0"}],["path",{"d":"M5 12.859a10 10 0 0 1 5.17-2.69"}],["path",{"d":"M19 12.859a10 10 0 0 0-2.007-1.523"}],["path",{"d":"M2 8.82a15 15 0 0 1 4.177-2.643"}],["path",{"d":"M22 8.82a15 15 0 0 0-11.288-3.764"}],["path",{"d":"m2 2 20 20"}]])
export const Wrench = /*#__PURE__*/createIcon('wrench', [["path",{"d":"M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"}]])
export const X = /*#__PURE__*/createIcon('x', [["path",{"d":"M18 6 6 18"}],["path",{"d":"m6 6 12 12"}]])
export const Zap = /*#__PURE__*/createIcon('zap', [["path",{"d":"M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"}]])
